[source.crates-io]
replace-with = "vendored-sources"

[source."git+https://github.com/Uniffi-Dart/uniffi-dart?rev=90f2c6f29cbf88c8bc2cf515e6a0c2314a48844c"]
git = "https://github.com/Uniffi-Dart/uniffi-dart"
rev = "90f2c6f29cbf88c8bc2cf515e6a0c2314a48844c"
replace-with = "vendored-sources"

[source.vendored-sources]
directory = "vendor"

[net]
offline = true
